export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
import { Outfit } from "next/font/google";

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Nabil Mustofa Portofolio</title>
      </head>
      <body className={`${outfit.variable} font-sans bg-neutral-950`}>
        {children}
      </body>
    </html>
  );
}
